name: CI

on:
  push:
    branches-ignore:
      - 'wip-*'
  pull_request:
    branches-ignore:
      - 'wip-*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all history for proper linting
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}

      # Lint codebase
      - name: Lint codebase
        uses: github/super-linter@v6
        continue-on-error: true
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: ${{ github.ref_name }}  # Use current branch as default
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # # Install backend dependencies
      # - name: Install backend dependencies
      #   run: |
      #     cd backend
      #     npm install

      # # Run backend unit tests
      # - name: Run backend unit tests
      #   run: |
      #     cd backend
      #     npm test

      # # Install frontend dependencies
      # - name: Install frontend dependencies
      #   run: |
      #     cd frontend
      #     npm install

      # # Run frontend unit tests
      # - name: Run frontend unit tests
      #   run: |
      #     cd frontend
      #     npm test

      # # (Optional) Build frontend
      # - name: Build frontend
      #   run: |
      #     cd frontend
      #     npm run build

      # # (Optional) Build backend
      # - name: Build backend
      #   run: |
      #     cd backend
      #     npm run build

      # # (Optional) Upload build artifacts
      # - name: Upload production build
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: react-build
      #     path: frontend/build/